/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "main.baml": "generator typescript {\n  output_type \"typescript\"\n  output_dir \"../\"\n  version \"0.223.0\"\n  module_format \"esm\"\n}\n\nclass BashArguments {\n  command string\n  timeout int?\n}\n\nclass BashCall {\n  tool \"bash\" @description(\"Select this whenever a shell command must run. Never claim a command ran in a final answer.\")\n  arguments BashArguments\n}\n\nclass ReadArguments {\n  path string\n  offset int?\n  limit int?\n}\n\nclass ReadCall {\n  tool \"read\" @description(\"Select this whenever file contents must be inspected before answering.\")\n  arguments ReadArguments\n}\n\nclass EditArguments {\n  path string\n  oldText string\n  newText string\n}\n\nclass EditCall {\n  tool \"edit\" @description(\"Select this to replace exact existing text in a file.\")\n  arguments EditArguments\n}\n\nclass WriteArguments {\n  path string\n  content string\n}\n\nclass WriteCall {\n  tool \"write\" @description(\"Select this to create or completely overwrite a file.\")\n  arguments WriteArguments\n}\n\nclass FinalAnswer {\n  tool \"final\" @description(\"Use only when no tool is needed or all required tool results already appear in the conversation.\")\n  content string\n}\n\nfunction NextAction(context: string) -> BashCall | ReadCall | EditCall | WriteCall | FinalAnswer {\n  client \"openai/gpt-4o-mini\"\n  prompt #\"\n    You are the decision layer for the Pi coding agent. Continue the supplied\n    conversation by selecting exactly one tool action, or return a final answer\n    when no tool is needed. If the user asks to run, inspect, edit, or write\n    something and no matching result is present yet, you MUST select the tool.\n    Never invent a tool result and never repeat an action that already has one.\n    Do not output markdown follow-up suggestions.\n\n    <conversation>\n    {{ context }}\n    </conversation>\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}