/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  BashArguments,  BashCall,  EditArguments,  EditCall,  FinalAnswer,  ReadArguments,  ReadCall,  WriteArguments,  WriteCall } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BashArguments {
      command?: string | null
      timeout?: number | null
    }
    export interface BashCall {
      tool?: "bash" | null
      arguments?: BashArguments | null
    }
    export interface EditArguments {
      path?: string | null
      oldText?: string | null
      newText?: string | null
    }
    export interface EditCall {
      tool?: "edit" | null
      arguments?: EditArguments | null
    }
    export interface FinalAnswer {
      tool?: "final" | null
      content?: string | null
    }
    export interface ReadArguments {
      path?: string | null
      offset?: number | null
      limit?: number | null
    }
    export interface ReadCall {
      tool?: "read" | null
      arguments?: ReadArguments | null
    }
    export interface WriteArguments {
      path?: string | null
      content?: string | null
    }
    export interface WriteCall {
      tool?: "write" | null
      arguments?: WriteArguments | null
    }
}